package com.smalltalk.SmallTalkFootball.services;

import com.smalltalk.SmallTalkFootball.domain.Fixture;
import com.smalltalk.SmallTalkFootball.enums.Language;
import com.smalltalk.SmallTalkFootball.enums.TeamType;
import com.smalltalk.SmallTalkFootball.models.OneLiner;
import com.smalltalk.SmallTalkFootball.system.exceptions.SmallTalkException;
import com.smalltalk.SmallTalkFootball.system.utils.prompts.PromptBuilder;
import com.smalltalk.SmallTalkFootball.system.utils.prompts.PromptBuilderFactory;
import com.smalltalk.SmallTalkFootball.testsupport.TestFixtures;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * One-liners are generated by an paid AI call, so the caching rules matter: a finished match
 * is generated once per team and language and then reused, while an upcoming match is
 * regenerated every time because the facts behind it are still changing.
 */
@ExtendWith(MockitoExtension.class)
class OneLinersServiceTest {

    private static final String GENERATED = "Cracking result for the Reds.";

    @Mock
    private FixtureService fixtureService;
    @Mock
    private AiService aiService;
    @Mock
    private PromptBuilderFactory promptBuilderFactory;
    @Mock
    private PromptBuilder promptBuilder;

    private OneLinersService service;

    @BeforeEach
    void setUp() {
        service = new OneLinersService(fixtureService, aiService, promptBuilderFactory);
        lenient().when(promptBuilderFactory.create(any(), any(), any())).thenReturn(promptBuilder);
        lenient().when(promptBuilder.buildPrompt()).thenReturn("a prompt");
        lenient().when(aiService.generate(anyString())).thenReturn(GENERATED);
    }

    private Fixture givenFixture(Fixture fixture) throws SmallTalkException {
        when(fixtureService.getFixture("fixture-1")).thenReturn(fixture);
        return fixture;
    }

    private static OneLiner cached(TeamType teamType, Language language, String text) {
        return OneLiner.builder().teamType(teamType).language(language).text(text).build();
    }

    @Test
    void reusesAStoredOneLinerForAFinishedMatch() throws SmallTalkException {
        Fixture fixture = givenFixture(TestFixtures.finishedFixture().build());
        fixture.addOneLiner(cached(TeamType.HOME, Language.BRITISH, "Stored take."));

        OneLiner result = service.getOneLiner("fixture-1", TeamType.HOME, Language.BRITISH);

        assertThat(result.getText()).isEqualTo("Stored take.");
        verifyNoInteractions(aiService);
        verify(fixtureService, never()).saveFixture(any());
    }

    @Test
    void generatesWhenTheStoredOneLinerIsForTheOtherTeam() throws SmallTalkException {
        Fixture fixture = givenFixture(TestFixtures.finishedFixture().build());
        fixture.addOneLiner(cached(TeamType.HOME, Language.BRITISH, "Stored take."));

        OneLiner result = service.getOneLiner("fixture-1", TeamType.AWAY, Language.BRITISH);

        assertThat(result.getText()).isEqualTo(GENERATED);
        verify(aiService).generate("a prompt");
    }

    @Test
    void generatesWhenTheStoredOneLinerIsInAnotherLanguage() throws SmallTalkException {
        Fixture fixture = givenFixture(TestFixtures.finishedFixture().build());
        fixture.addOneLiner(cached(TeamType.HOME, Language.BRITISH, "Stored take."));

        OneLiner result = service.getOneLiner("fixture-1", TeamType.HOME, Language.HEBREW);

        assertThat(result.getText()).isEqualTo(GENERATED);
        assertThat(result.getLanguage()).isEqualTo(Language.HEBREW);
    }

    @Test
    void storesANewlyGeneratedOneLinerForAFinishedMatch() throws SmallTalkException {
        Fixture fixture = givenFixture(TestFixtures.finishedFixture().build());

        OneLiner result = service.getOneLiner("fixture-1", TeamType.HOME, Language.BRITISH);

        assertThat(fixture.getOneLiners()).containsExactly(result);
        verify(fixtureService).saveFixture(fixture);
    }

    @Test
    void tagsTheGeneratedOneLinerWithItsTeamAndLanguage() throws SmallTalkException {
        givenFixture(TestFixtures.finishedFixture().build());

        OneLiner result = service.getOneLiner("fixture-1", TeamType.AWAY, Language.AMERICAN);

        assertThat(result.getTeamType()).isEqualTo(TeamType.AWAY);
        assertThat(result.getLanguage()).isEqualTo(Language.AMERICAN);
        assertThat(result.getText()).isEqualTo(GENERATED);
    }

    /*
     * The facts behind an upcoming match keep changing, so its one-liner is never cached.
     */
    @Test
    void neverStoresAOneLinerForAnUpcomingMatch() throws SmallTalkException {
        Fixture fixture = givenFixture(TestFixtures.upcomingFixture().build());

        OneLiner result = service.getOneLiner("fixture-1", TeamType.HOME, Language.BRITISH);

        assertThat(result.getText()).isEqualTo(GENERATED);
        assertThat(fixture.getOneLiners()).isEmpty();
        verify(fixtureService, never()).saveFixture(any());
    }

    @Test
    void regeneratesForAnUpcomingMatchEvenWhenOneIsAlreadyStored() throws SmallTalkException {
        Fixture fixture = givenFixture(TestFixtures.upcomingFixture().build());
        fixture.addOneLiner(cached(TeamType.HOME, Language.BRITISH, "Stale preview."));

        OneLiner result = service.getOneLiner("fixture-1", TeamType.HOME, Language.BRITISH);

        assertThat(result.getText()).isEqualTo(GENERATED);
        verify(aiService).generate("a prompt");
    }

    @Test
    void buildsThePromptForTheRequestedTeamAndLanguage() throws SmallTalkException {
        Fixture fixture = givenFixture(TestFixtures.finishedFixture().build());

        service.getOneLiner("fixture-1", TeamType.AWAY, Language.HEBREW);

        verify(promptBuilderFactory).create(fixture, TeamType.AWAY, Language.HEBREW);
    }

    @Test
    void supportsAOneLinerWithNoPreferredTeam() throws SmallTalkException {
        givenFixture(TestFixtures.finishedFixture().build());

        OneLiner result = service.getOneLiner("fixture-1", null, Language.BRITISH);

        assertThat(result.getTeamType()).isNull();
        assertThat(result.getText()).isEqualTo(GENERATED);
    }
}
