package com.smalltalk.SmallTalkFootball.entities;


public enum InfoCategory {
    INTRO, RULES, POSITIONS, GAME_STRUCTURE, COMPETITIONS, PLAYER_SKILLS, FORMATIONS, OFFICIATING, FIELD_AND_EQUIPMENT, FAN_CULTURE;

}